baseURL = 'https://mighty1.nl'
languageCode = 'nl'
title = 'Mighty 1'
theme = 'mighty1'
paginate = 9999
[permalinks]
  posts = "/:filename/"
  pages = "/:filename/"
  categories = "/:slug/"
[params]
  favicon = "favicon.icon"

