baseURL = 'https://mighty1.netlify.app'
languageCode = 'nl'
title = 'Mighty 1'
theme = 'mighty1'
[permalinks]
  posts = "/:filename/"
  pages = "/:filename/"
  categories = "/:slug/"
[params]
  favicon = "favicon.icon"

